recordTypes:
  - flowLog
portNaming:
  enable: true
  portNames:
    "3100": loki
quickFilters:
  - name: Applications
    filter:
      src_namespace!: 'openshift-,netobserv'
      dst_namespace!: 'openshift-,netobserv'
    default: true
  - name: Infrastructure
    filter:
      src_namespace: 'openshift-,netobserv'
      dst_namespace: 'openshift-,netobserv'
  - name: Pods network
    filter:
      src_kind: 'Pod'
      dst_kind: 'Pod'
    default: true
  - name: Services network
    filter:
      dst_kind: 'Service'
alertNamespaces:
  - netobserv
sampling: 50
features:
  - pktDrop
  - dnsTracking
